"""addProxyandValidates

Revision ID: 9613b016b79d
Revises: e7769a1e270c
Create Date: 2026-04-25 20:31:18.060014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9613b016b79d'
down_revision = 'e7769a1e270c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('equipment_needed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.alter_column('duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.alter_column('duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sets',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reps',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('equipment_needed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
